### ISSUE TITLE
python 3.7?

### ISSUE THREAD

**Issue by vict0rsch** [powerapi-ng/pyJoules#11]
Why is there a restriction to python >= 3.7 ? Could this be lossened?

**Comment by altor** [comment]
Hello
We use tools that are only available since 3.7 version like recursive type hint, [dataclass](https://docs.python.org/fr/3/library/dataclasses.html) and [`time.time_ns`](https://docs.python.org/fr/3/library/time.html#time.time_ns) function.
This tools are not mandatory and could be replaced easly with 3.6 compatible tools.

So if you need python 3.6 compatibility, i can quickly lower the requirements

**Comment by vict0rsch** [comment]
"Python 3.6 is still supported until december 2021 (according to https://endoflife.date/python). Supporting other "un-supported" Python versions would required additional maintaining work but would allow to reach more potential users. I think the minimum would be at least Python 3.6" from a co-dev at code-carbon so yeah that would be great :)

**Comment by altor** [comment]
Ok, new version of pyJoules (https://github.com/powerapi-ng/pyJoules/releases/tag/v0.4.0) now support python3.6
